version: '3'
services:
  camunda:
    image: camunda/camunda-bpm-platform:${DISTRO:-latest}
    ports:
      - "9000:8080"
    restart: unless-stopped
  camunda-postgres:
    image: camunda/camunda-bpm-platform:${DISTRO:-latest}
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=postgres:5432
    links:
      - postgres
    ports:
      - "9001:8080"
    restart: unless-stopped
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
volumes:
  pgdbdata: null